# Generated by Django 3.1 on 2020-10-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_address', models.CharField(max_length=200)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_phone_number', models.IntegerField()),
                ('doctor_working_hospital', models.ManyToManyField(to='hospital.Hospital')),
            ],
        ),
    ]
