# Generated by Django 3.1 on 2020-10-31 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('hospital_email', models.EmailField(max_length=254)),
                ('hospital_address', models.CharField(max_length=100)),
                ('hospital_phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HospitalUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.CharField(max_length=100)),
                ('instagram_url', models.CharField(max_length=100)),
                ('hospital_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_types', models.CharField(choices=[('O+', 'O-Positive'), ('O-', 'O-Negative'), ('A+', 'A-Positive'), ('A-', 'A-Negative'), ('B+', 'B-Positive'), ('B-', 'B-Negative'), ('AB+', 'AB-Positive'), ('AB-', 'AB-Negative')], max_length=5)),
                ('blood_hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospital.hospital')),
            ],
        ),
    ]
